### ISSUE TITLE
Attempt to load unavailable song continually retries

### ISSUE THREAD

**Issue by eharris** [einsteinx2/iSub3#13]
I've noticed that when I have a playlist that has a song that has been removed (or moved) that iSub seems to keep retrying playing that song, which effectively stalls any further playback.

Best would be if it realizes the file isn't available (not sure what the server is returning that might indicate that) but it should at least give up after some reasonable number of tries.

**Comment by einsteinx2** [comment]
Unfortunately this project is dead and I no longer use it personally, develop it, or support it. When I stopped working on it, I open sourced it and made it free in the App Store in case anyone wanted to continue with it, but otherwise I'm no longer involved.
